const statusEl=document.getElementById("status"),appliedEl=document.getElementById("applied"),skippedEl=document.getElementById("skipped"),eventsEl=document.getElementById("events"),startEl=document.getElementById("start"),stopEl=document.getElementById("stop"),setupEl=document.getElementById("setup"),roleEl=document.getElementById("quickRole"),locationEl=document.getElementById("quickLocation");
let initialized=false;
function installLocationRecommendations(){
  const codes="AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW".split(" ");
  const names=new Intl.DisplayNames(["en"],{type:"region"}),countries=codes.map(code=>names.of(code)).filter(Boolean);
  const hubs=["Remote — Worldwide","New York City","San Francisco Bay Area","Los Angeles","Seattle","Austin","Boston","Chicago","Toronto","Vancouver","Mexico City","São Paulo","Buenos Aires","London","Dublin","Amsterdam","Berlin","Munich","Paris","Madrid","Barcelona","Lisbon","Zurich","Stockholm","Copenhagen","Oslo","Helsinki","Warsaw","Prague","Vienna","Milan","Bengaluru","Hyderabad","Mumbai","Delhi NCR","Pune","Chennai","Kolkata","Ahmedabad","Gurugram","Noida","Singapore","Tokyo","Seoul","Hong Kong","Shanghai","Beijing","Shenzhen","Taipei","Bangkok","Kuala Lumpur","Jakarta","Manila","Ho Chi Minh City","Dubai","Abu Dhabi","Riyadh","Doha","Tel Aviv","Istanbul","Sydney","Melbourne","Brisbane","Auckland","Johannesburg","Cape Town","Nairobi","Lagos","Cairo"];
  const places=["Worldwide",...countries,...hubs].filter((value,index,array)=>array.indexOf(value)===index);
  document.getElementById("locationList").innerHTML=places.map(place=>'<option value="'+escapeHtml(place)+'"></option>').join("");
  const hint=document.createElement("p");hint.className="place-hint";hint.textContent="Worldwide = every location. Or type any country, city, or region.";locationEl.closest("label").appendChild(hint);
}
function refresh(){chrome.runtime.sendMessage({type:"SIFT_STATUS"},r=>{const s=r?.status||{};if(!initialized){roleEl.value=r?.profile?.role||"Data Analyst";locationEl.value=r?.profile?.location||"Worldwide";initialized=true}statusEl.textContent=s.message||"Ready";appliedEl.textContent=s.applied||0;skippedEl.textContent=s.skipped||0;eventsEl.innerHTML=(s.events||[]).map(e=>'<div><b>'+escapeHtml(e.job||"Job")+'</b><span>'+escapeHtml(e.reason||"")+'</span></div>').join("");startEl.disabled=!!s.active;stopEl.disabled=!s.active})}
function escapeHtml(value){const div=document.createElement("div");div.textContent=String(value);return div.innerHTML}
startEl.onclick=async()=>{const saved=await chrome.storage.local.get("profile"),profile={...(saved.profile||{}),role:roleEl.value.trim(),location:locationEl.value.trim()||"Worldwide"};await chrome.storage.local.set({profile});chrome.runtime.sendMessage({type:"SIFT_START"},r=>{if(!r?.ok)statusEl.textContent=r?.error||"Could not start";refresh()})};
stopEl.onclick=()=>chrome.runtime.sendMessage({type:"SIFT_STOP"},refresh);
setupEl.onclick=()=>chrome.runtime.openOptionsPage();
setInterval(refresh,1000);
installLocationRecommendations();refresh();
