const STORE="sift-v2";
const ROLE_SUGGESTIONS=["Data Analyst","Senior Data Analyst","Junior Data Analyst","Business Data Analyst","Product Data Analyst","Business Intelligence Analyst","BI Analyst","Reporting Analyst","Marketing Data Analyst","Operations Analyst","SQL Analyst","Data Quality Analyst","Analytics Consultant"];
const LOCATION_SUGGESTIONS=["Hyderabad","Hyderabad, Telangana","Greater Hyderabad Area","Secunderabad, Telangana","HITEC City, Hyderabad","Gachibowli, Hyderabad","Madhapur, Hyderabad","Kondapur, Hyderabad","Remote — Hyderabad"];
const defaults={profile:{name:"",email:"",headline:"",skills:[],resumeName:"",resumeText:"",roles:["Data Analyst"],location:"Hyderabad",mode:"Any",setup:false},opportunities:[],queue:[],activity:[],selectedQueue:null,filter:"all",reminder:false};
let state=load(),setupStep=1;
function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(STORE)||"{}"))}catch(e){return JSON.parse(JSON.stringify(defaults))}}
function persist(render=true){localStorage.setItem(STORE,JSON.stringify(state));if(render)renderAll()}
function esc(v){const d=document.createElement("div");d.textContent=v==null?"":String(v);return d.innerHTML}
function initials(v){return(v||"You").split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase()}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function toast(m){const e=document.getElementById("toast");e.textContent=m;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2400)}
function closeModal(id){document.getElementById(id).classList.add("hidden")}
function installAutocomplete(){
  const addList=(id,values)=>{const list=document.createElement("datalist");list.id=id;list.innerHTML=values.map(v=>'<option value="'+esc(v)+'"></option>').join("");document.body.appendChild(list)};
  addList("roleSuggestions",ROLE_SUGGESTIONS);addList("locationSuggestions",LOCATION_SUGGESTIONS);
  ["settingsRoleInput","onboardRoleInput","addTitle"].forEach(id=>{const el=document.getElementById(id);if(el){el.setAttribute("list","roleSuggestions");el.setAttribute("autocomplete","off")}});
  ["setLocation","onboardLocation"].forEach(id=>{const el=document.getElementById(id);if(el){el.setAttribute("list","locationSuggestions");el.setAttribute("autocomplete","off")}});
  const roleHint=document.createElement("div");roleHint.className="autocomplete-hint";roleHint.textContent="⌨ Start typing to see role suggestions";settingsRoleInput.closest("label").appendChild(roleHint);
  const locationHint=document.createElement("div");locationHint.className="autocomplete-hint";locationHint.textContent="⌖ Start typing to see Hyderabad-area suggestions";setLocation.closest("label").appendChild(locationHint);
  const guardrail=document.querySelector("#settingsView .settings-grid>.grid .settings:last-child");
  if(guardrail){const mode=document.createElement("div");mode.className="apply-mode";mode.innerHTML='<span>APPLICATION MODE</span><strong>Auto Apply companion</strong><p>After one-time extension setup, SIFT opens LinkedIn, uploads your resume, and submits exact-match Easy Apply jobs.</p><button type="button" onclick="startAutoApply()">Start auto apply ↗</button>';guardrail.appendChild(mode)}
}
function startAutoApply(){
  if(!state.profile.setup){openSetup();return}
  let acknowledged=false;
  const receive=event=>{
    if(event.data?.type==="SIFT_EXTENSION_ACK")acknowledged=true;
    if(event.data?.type==="SIFT_AUTO_APPLY_RESULT"){
      window.removeEventListener("message",receive);
      if(event.data.ok){toast("Auto Apply started in LinkedIn");log("Started Auto Apply run","↗");persist()}
      else alert(event.data.error);
    }
  };
  window.addEventListener("message",receive);
  window.postMessage({type:"SIFT_AUTO_APPLY_START",brief:{role:state.profile.roles[0],location:state.profile.location}},"*");
  setTimeout(()=>{if(!acknowledged){window.removeEventListener("message",receive);alert("SIFT Auto Apply extension is not installed yet. In Chrome, open chrome://extensions, enable Developer mode, choose Load unpacked, and select the extension folder inside this project.")}},900);
}
function log(text,icon="✦"){state.activity.unshift({text,icon,at:new Date().toLocaleDateString(undefined,{month:"short",day:"numeric"})});state.activity=state.activity.slice(0,8)}
function safeUrl(v){try{const u=new URL(v);return["http:","https:"].includes(u.protocol)?u.href.replace(/'/g,"%27"):"#"}catch(e){return"#"}}
function showView(name){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.getElementById(name+"View").classList.add("active");document.querySelectorAll(".nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===name));pageTitle.textContent={dashboard:"Overview",discover:"Discover opportunities",pipeline:"Application pipeline",review:"Review queue",settings:"Agent setup"}[name];window.scrollTo({top:0,behavior:"smooth"});renderAll()}
document.querySelectorAll(".nav button").forEach(x=>x.onclick=()=>showView(x.dataset.view));
document.querySelectorAll(".filter").forEach(x=>x.onclick=()=>{document.querySelectorAll(".filter").forEach(y=>y.classList.remove("active"));x.classList.add("active");state.filter=x.dataset.filter;renderJobs()});
document.querySelectorAll(".toggle").forEach(x=>x.onclick=()=>{if(!x.id)return;x.classList.toggle("on");state.reminder=x.classList.contains("on");persist(false);if(state.reminder&&"Notification"in window)Notification.requestPermission()});
function renderAll(){const o=state.opportunities.filter(strictMatch),a=o.filter(x=>x.status==="applied").length,s=o.map(x=>x.score||0),role=state.profile.roles[0]||"Target role",city=state.profile.location||"Target city";avatar.textContent=initials(state.profile.name);statMatches.textContent=o.length;statReview.textContent=state.queue.length;statApplied.textContent=a;statScore.textContent=s.length?Math.round(s.reduce((x,y)=>x+y,0)/s.length)+"%":"—";runHeading.textContent=role+" in "+city;runDescription.textContent="Strict mode rejects every unrelated title and location before it reaches your feed.";focusRole.textContent=role;focusLocation.textContent=city;discoverLead.textContent="Showing only "+role+" opportunities in "+city+". Everything else is removed.";renderActivity();renderGoals();renderJobs();renderPipeline();renderQueue();populateSettings()}
function renderActivity(){const rows=state.activity.length?state.activity:[{text:"Complete your profile to start the agent",icon:"→",at:"Now"},{text:"Strict role and city filter is active",icon:"✓",at:"Ready"}];activityList.innerHTML=rows.map(x=>'<div class="activity-row"><div class="activity-icon">'+esc(x.icon)+'</div><div class="activity-copy"><strong>'+esc(x.text)+'</strong><span>SIFT agent</span></div><div class="activity-time">'+esc(x.at)+'</div></div>').join("")}
function renderGoals(){const a=state.opportunities.filter(x=>x.status==="applied").length,c=state.opportunities.filter(x=>x.actionType==="comment"&&x.status==="applied").length,e=state.opportunities.filter(x=>x.actionType==="email"&&x.status==="applied").length,p=Math.min(100,Math.round((a/10+c/3+e/3)/3*100));goalPct.textContent=p+"%";goalApps.textContent=a+" / 10";goalComments.textContent=c+" / 3";goalEmails.textContent=e+" / 3";goalRing.style.background="conic-gradient(var(--lime) 0 "+p+"%,#e4e5db "+p+"%)"}
function strictMatch(j){const title=(j.title||"").toLowerCase(),body=(j.description||"").toLowerCase(),place=(j.location||"").toLowerCase(),roles=state.profile.roles.map(x=>x.toLowerCase()),city=(state.profile.location||"").toLowerCase();const roleOK=roles.some(r=>j.type==="post"?(title+" "+body).includes(r):title.includes(r));return roleOK&&(!city||place.includes(city))}
function filtered(){const q=(searchInput.value||"").toLowerCase();return state.opportunities.filter(j=>{const h=[j.title,j.company,j.location,j.description,...(j.tags||[])].join(" ").toLowerCase(),f=state.filter;return strictMatch(j)&&(!q||h.includes(q))&&(f==="all"||f===j.type)}).sort((a,b)=>b.score-a.score)}
function renderJobs(){const jobs=filtered();if(!jobs.length){jobList.innerHTML='<div class="card empty"><div class="empty-icon">⌕</div><strong>No matches here yet</strong><p>Run the agent or add a LinkedIn job or post URL.</p><button class="btn green small" onclick="openAdd()">Add opportunity</button></div>';return}jobList.innerHTML=jobs.map(j=>'<article class="card job"><div class="job-top"><div class="logo">'+esc(initials(j.company))+'</div><div class="job-info"><div class="job-title">'+esc(j.title)+'</div><div class="job-company">'+esc(j.company)+' · '+esc(j.location)+'</div></div><div class="score">'+j.score+'%</div></div><div class="tags">'+(j.tags||[]).map((t,i)=>'<span class="tag '+(i<2?"match":"")+'">'+esc(t)+'</span>').join("")+'</div><p class="job-copy">'+esc(j.description)+'</p><div class="job-bottom"><div class="source">'+(j.type==="post"?"◉":"▣")+' '+esc(j.source)+' · '+esc(j.added)+'</div><div class="job-actions"><button class="btn ghost small" onclick="window.open(\''+safeUrl(j.url)+'\',\'_blank\',\'noopener\')">View ↗</button><button class="btn green small" onclick="prepareDraft(\''+j.id+'\')">'+(state.queue.some(q=>q.jobId===j.id)?"Review draft":"Prepare draft")+'</button></div></div></article>').join("")}
function score(j){const t=[j.title,j.description,j.location].join(" ").toLowerCase();let s=55;state.profile.roles.forEach(r=>{if(t.includes(r.toLowerCase()))s+=20});state.profile.skills.forEach(k=>{if(t.includes(k.toLowerCase()))s+=4});if(state.profile.mode==="Any"||t.includes(state.profile.mode.toLowerCase()))s+=5;if(state.profile.location&&t.includes(state.profile.location.toLowerCase().split(",")[0]))s+=5;return Math.max(45,Math.min(96,s))}
function runAgent(button){if(!state.profile.setup){openSetup();return}openLinkedInSearch();log("Opened exact search: "+state.profile.roles[0]+" in "+state.profile.location,"⌕");persist();showView("discover");toast("Live exact-match search opened. Paste strong results back into SIFT")}
function handleSearch(){const q=searchInput.value.trim();if(/^https?:\/\//i.test(q)){addUrl.value=q;openAdd()}else renderJobs()}
function openLinkedInSearch(){const r=state.profile.roles.length?state.profile.roles.join(" OR "):"hiring",l=state.profile.location?"&location="+encodeURIComponent(state.profile.location):"";window.open("https://www.linkedin.com/jobs/search/?keywords="+encodeURIComponent(r)+l,"_blank","noopener")}
function openAdd(){addModal.classList.remove("hidden")}
function extractTags(t){const k=["Figma","React","Python","JavaScript","Research","Design systems","AI","B2B","Product","SQL"],f=k.filter(x=>t.toLowerCase().includes(x.toLowerCase()));return(f.length?f:["Shared link","Needs review"]).slice(0,4)}
function addOpportunity(){const url=addUrl.value.trim(),title=addTitle.value.trim(),company=addCompany.value.trim();if(!url||!title||!company){toast("Add the URL, role, and company");return}const type=addType.value,description=addDescription.value.trim(),city=state.profile.location||"",hasCity=(title+" "+description).toLowerCase().includes(city.toLowerCase()),j={id:uid(),url,title,company,type,description:description||"Shared opportunity",email:addEmail.value.trim(),location:hasCity?city:"Location not verified",tags:extractTags(description),source:type==="post"?"LinkedIn Post":"Shared Job",added:"Just now",status:"matched"};if(!strictMatch(j)){toast("Rejected: this is not "+state.profile.roles[0]+" in "+city);return}j.score=score(j);state.opportunities.push(j);log("Qualified: "+title+" at "+company,type==="post"?"◉":"▣");closeModal("addModal");["addUrl","addTitle","addCompany","addEmail","addDescription"].forEach(id=>document.getElementById(id).value="");persist();toast("Exact match accepted at "+j.score+"%")}
function draftFor(j){const n=state.profile.name||"Candidate",f=n.split(" ")[0],skills=state.profile.skills.slice(0,3).join(", ")||"relevant product experience";if(j.type==="post")return{type:"comment",subject:"",body:"Thanks for sharing this, "+j.company.split(" ")[0]+". The "+j.title+" opportunity stood out, especially the focus on "+(j.tags[0]||"meaningful products")+". I bring experience in "+skills+" and would love to learn more. — "+f};if(j.email)return{type:"email",subject:"Application: "+j.title+" — "+n,body:"Hi "+j.company+" hiring team,\n\nI am reaching out about the "+j.title+" role. My background in "+skills+" aligns well with what you are building, especially "+(j.tags[0]||"the product challenge")+" highlighted in the role.\n\nI would welcome the chance to discuss how my experience could contribute. My resume is ready to attach.\n\nBest,\n"+n};return{type:"application",subject:"Application note",body:"I am excited to apply for the "+j.title+" role at "+j.company+". My experience with "+skills+" maps closely to the role, particularly its emphasis on "+(j.tags.slice(0,2).join(" and ")||"thoughtful execution")+". I would bring a practical, collaborative approach and a strong focus on measurable outcomes."}}
function prepareDraft(id){let q=state.queue.find(x=>x.jobId===id);const j=state.opportunities.find(x=>x.id===id);if(!j)return;if(!q){const d=draftFor(j);q={id:uid(),jobId:id,type:d.type,subject:d.subject,body:d.body};state.queue.push(q);j.status="ready";j.actionType=d.type;log("Draft prepared for "+j.company,"✎");persist()}state.selectedQueue=q.id;persist(false);showView("review")}
function stage(s){return{matched:"Matched",ready:"Ready",applied:"Applied"}[s]||"Matched"}
function renderPipeline(){const qualified=state.opportunities.filter(strictMatch);if(!qualified.length){pipelineRows.innerHTML='<div class="empty"><div class="empty-icon">◫</div><strong>No qualified roles yet</strong><p>Only exact role and city matches appear here.</p><button class="btn green small" onclick="showView(\'discover\')">Run strict search</button></div>';return}pipelineRows.innerHTML=qualified.map(j=>'<div class="pipe-row"><div class="company"><div class="logo">'+esc(initials(j.company))+'</div><div><strong>'+esc(j.title)+'</strong><span>'+esc(j.company)+'</span></div></div><span>'+esc(j.type==="post"?"Hiring post":"Job listing")+'</span><span><span class="stage stage-'+esc(j.status||"matched")+'">'+esc(stage(j.status))+'</span></span><span>'+esc(j.added)+'</span><span><button class="link" onclick="prepareDraft(\''+j.id+'\')">Open</button></span></div>').join("")}
function renderQueue(){queueCount.textContent=state.queue.length+" item"+(state.queue.length===1?"":"s");if(!state.queue.length){queueList.innerHTML='<div class="empty"><strong>No pending drafts</strong></div>';reviewDetail.innerHTML='<div class="empty"><div class="empty-icon">✓</div><strong>You are all caught up</strong><p>New application notes, emails, and comments appear here.</p><button class="btn green small" onclick="showView(\'discover\')">Find opportunities</button></div>';return}if(!state.selectedQueue||!state.queue.some(q=>q.id===state.selectedQueue))state.selectedQueue=state.queue[0].id;queueList.innerHTML=state.queue.map(q=>{const j=state.opportunities.find(x=>x.id===q.jobId)||{};return'<button class="queue-item '+(q.id===state.selectedQueue?"active":"")+'" onclick="selectQueue(\''+q.id+'\')"><div class="qtype">'+(q.type==="email"?"✉":q.type==="comment"?"◉":"↗")+'</div><div><strong>'+esc(j.title||"Opportunity")+'</strong><span>'+esc(j.company||"")+' · '+esc(q.type)+'</span></div></button>'}).join("");const q=state.queue.find(x=>x.id===state.selectedQueue),j=state.opportunities.find(x=>x.id===q.jobId)||{};reviewDetail.innerHTML='<div class="review-meta"><div><h3>'+esc(j.title)+'</h3><p>'+esc(j.company)+' · '+esc(j.location)+'</p></div><span class="stage stage-ready">'+esc(q.type)+'</span></div>'+(q.type==="email"?'<div class="draft-label">Subject</div><input class="draft" id="draftSubject" value="'+esc(q.subject)+'">':'')+'<div class="draft-label">'+(q.type==="comment"?"Comment":"Message")+'</div><textarea class="draft" id="draftBody" rows="10">'+esc(q.body)+'</textarea><div class="note">Verify the listing and recipient. Your mail app opens so you can attach the resume yourself.</div><div class="review-actions"><button class="btn danger small" onclick="dismissDraft(\''+q.id+'\')">Dismiss</button><div><button class="btn ghost small" onclick="saveDraft(\''+q.id+'\')">Save edit</button><button class="btn primary" onclick="approveDraft(\''+q.id+'\')">Approve & open ↗</button></div></div>'}
function selectQueue(id){state.selectedQueue=id;persist(false);renderQueue()}
function saveDraft(id){const q=state.queue.find(x=>x.id===id);if(!q)return;q.body=draftBody.value;if(window.draftSubject)q.subject=draftSubject.value;persist(false);toast("Draft saved")}
async function approveDraft(id){saveDraft(id);const q=state.queue.find(x=>x.id===id),j=state.opportunities.find(x=>x.id===q.jobId);if(q.type==="email")location.href="mailto:"+encodeURIComponent(j.email)+"?subject="+encodeURIComponent(q.subject)+"&body="+encodeURIComponent(q.body);else{try{await navigator.clipboard.writeText(q.body);toast("Draft copied. Paste it after reviewing the page")}catch(e){toast("Open the page and copy your reviewed draft")}window.open(j.url,"_blank","noopener")}j.status="applied";log((q.type==="email"?"Email opened for ":q.type==="comment"?"Comment approved for ":"Application opened for ")+j.company,"↗");state.queue=state.queue.filter(x=>x.id!==id);state.selectedQueue=state.queue[0]?.id||null;persist()}
function dismissDraft(id){const q=state.queue.find(x=>x.id===id),j=state.opportunities.find(x=>x.id===q?.jobId);if(j)j.status="matched";state.queue=state.queue.filter(x=>x.id!==id);state.selectedQueue=state.queue[0]?.id||null;persist();toast("Draft dismissed")}
function populateSettings(){if(["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName))return;const p=state.profile,v={setName:p.name,setEmail:p.email,setHeadline:p.headline,setSkills:p.skills.join(", "),setResumeText:p.resumeText,setLocation:p.location,setMode:p.mode};Object.entries(v).forEach(([id,val])=>document.getElementById(id).value=val||"");resumeName.textContent=p.resumeName||"No resume uploaded";renderSettingsRoles();reminderToggle.classList.toggle("on",!!state.reminder)}
function saveSettings(){const p=state.profile;p.name=setName.value.trim();p.email=setEmail.value.trim();p.headline=setHeadline.value.trim();p.skills=setSkills.value.split(",").map(x=>x.trim()).filter(Boolean);p.resumeText=setResumeText.value.trim();p.location=setLocation.value.trim();p.mode=setMode.value;p.setup=!!(p.name&&p.roles.length&&p.location);state.opportunities=state.opportunities.filter(strictMatch);log("Strict brief locked: "+p.roles[0]+" in "+p.location,"✓");persist();toast("Brief locked. Unrelated results removed")}
function addSettingsRole(){const v=settingsRoleInput.value.trim();if(v&&!state.profile.roles.includes(v)){state.profile.roles.push(v);settingsRoleInput.value="";persist()}}
function removeRole(i){state.profile.roles.splice(i,1);persist()}function renderSettingsRoles(){settingsRoles.innerHTML=state.profile.roles.map((r,i)=>'<span class="chip">'+esc(r)+' <button onclick="removeRole('+i+')">×</button></span>').join("")||'<span class="muted">No roles added yet</span>'}
function openSetup(){setupStep=state.profile.setup?2:1;renderSetup();setupModal.classList.remove("hidden")}
function renderSetup(){[1,2,3].forEach(n=>document.getElementById("setup"+n).classList.toggle("hidden",n!==setupStep));bar2.classList.toggle("on",setupStep>=2);bar3.classList.toggle("on",setupStep>=3);setupBack.classList.toggle("hidden",setupStep===1);setupNext.textContent=setupStep===3?"Start searching":"Continue";onboardName.value=state.profile.name;onboardLocation.value=state.profile.location;onboardMode.value=state.profile.mode;renderOnboardRoles()}
function goNext(){if(setupStep===1){setupStep=2;renderSetup();return}if(setupStep===2){const n=onboardName.value.trim();if(!n||!state.profile.roles.length){toast("Add your name and at least one target role");return}state.profile.name=n;state.profile.location=onboardLocation.value.trim();state.profile.mode=onboardMode.value;setupStep=3;renderSetup();return}state.profile.setup=true;log("Search agent configured","✓");persist();closeModal("setupModal");runAgent()}
function goBack(){setupStep=Math.max(1,setupStep-1);renderSetup()}function addOnboardRole(){const v=onboardRoleInput.value.trim();if(v&&!state.profile.roles.includes(v)){state.profile.roles.push(v);onboardRoleInput.value="";renderOnboardRoles()}}function removeOnboardRole(i){state.profile.roles.splice(i,1);renderOnboardRoles()}function renderOnboardRoles(){onboardRoles.innerHTML=state.profile.roles.map((r,i)=>'<span class="chip">'+esc(r)+' <button onclick="removeOnboardRole('+i+')">×</button></span>').join("")}
async function handleFile(file){if(!file)return;if(file.size>8*1024*1024){toast("Choose a file smaller than 8 MB");return}state.profile.resumeName=file.name;onboardFile.textContent="✓ "+file.name;resumeName.textContent=file.name;if(file.type==="text/plain"||file.name.toLowerCase().endsWith(".txt")){state.profile.resumeText=(await file.text()).slice(0,30000);const words=["JavaScript","Python","React","Figma","SQL","Product","Research","Design systems"];state.profile.skills=[...new Set(state.profile.skills.concat(words.filter(x=>state.profile.resumeText.toLowerCase().includes(x.toLowerCase()))))]}persist(false);toast("Resume added locally")}
["onboardResume","resumeInput"].forEach(id=>document.getElementById(id).onchange=e=>handleFile(e.target.files[0]));["dragenter","dragover"].forEach(n=>dropzone.addEventListener(n,e=>{e.preventDefault();dropzone.classList.add("drag")}));["dragleave","drop"].forEach(n=>dropzone.addEventListener(n,e=>{e.preventDefault();dropzone.classList.remove("drag")}));dropzone.ondrop=e=>handleFile(e.dataTransfer.files[0]);onboardRoleInput.onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();addOnboardRole()}};settingsRoleInput.onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();addSettingsRole()}};
function exportData(){const rows=[["Role","Company","Type","Score","Status","URL"],...state.opportunities.filter(strictMatch).map(x=>[x.title,x.company,x.type,x.score,x.status,x.url])],csv=rows.map(r=>r.map(v=>'"'+String(v||"").replace(/"/g,'""')+'"').join(",")).join("\n"),blob=new Blob([csv],{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="sift-pipeline.csv";a.click();URL.revokeObjectURL(a.href);toast("Pipeline exported")}
installAutocomplete();if(!state.profile.setup)setTimeout(openSetup,350);renderAll();
